FROM node:latest as node

WORKDIR /app

COPY . .

RUN npm install

RUN npm run build --prod


#Stage 2, creating nginx server for application in container.

FROM nginx:alpine
COPY --from=node /app/dist/demo-app /usr/share/nginx/html